{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "Treedraw",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Treedraw-1.0.0.jar",
          "url": "Treedraw-1.0.0.jar",
          "size": 42953,
          "sha512": "b9564e7d59de7d15546e9512e0f54dfc00901d555d463a2a61972943423c36b44622aeb674f3884a86b3e110a2679f936dfd861ff46255d95273981db228ef8f",
          "sha256": "7de1830e38d77251f986f4012232cba4aa263ff4d69e8900df6e3facb59645b6",
          "sha1": "76814a582da39d29b62a1175944cf2e41d7a0f20",
          "md5": "cc7984b8851025445326420c6fb7001a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Treedraw-1.0.0.jar",
          "url": "Treedraw-1.0.0.jar",
          "size": 42953,
          "sha512": "b9564e7d59de7d15546e9512e0f54dfc00901d555d463a2a61972943423c36b44622aeb674f3884a86b3e110a2679f936dfd861ff46255d95273981db228ef8f",
          "sha256": "7de1830e38d77251f986f4012232cba4aa263ff4d69e8900df6e3facb59645b6",
          "sha1": "76814a582da39d29b62a1175944cf2e41d7a0f20",
          "md5": "cc7984b8851025445326420c6fb7001a"
        }
      ]
    }
  ]
}
