{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "Treedraw",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Treedraw-1.0.0.jar",
          "url": "Treedraw-1.0.0.jar",
          "size": 42971,
          "sha512": "6ef06168b2ec34169bbfb6db219202dbdac176d8a65f321360473311dcb8d2a241ee6c094cd6ebf9578400e1f2f9c9b46eb11af69b38026f70e21db9643a1253",
          "sha256": "32d03d43408d379b913c84eb461704ba5834d7a60cd4bbc98e63b89b27e96e73",
          "sha1": "9b514839a14ec2ebc0d52a0ac7d8a0fc179e1151",
          "md5": "5ea2135dfd866ce0c6607f0707ad7e76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Treedraw-1.0.0.jar",
          "url": "Treedraw-1.0.0.jar",
          "size": 42971,
          "sha512": "6ef06168b2ec34169bbfb6db219202dbdac176d8a65f321360473311dcb8d2a241ee6c094cd6ebf9578400e1f2f9c9b46eb11af69b38026f70e21db9643a1253",
          "sha256": "32d03d43408d379b913c84eb461704ba5834d7a60cd4bbc98e63b89b27e96e73",
          "sha1": "9b514839a14ec2ebc0d52a0ac7d8a0fc179e1151",
          "md5": "5ea2135dfd866ce0c6607f0707ad7e76"
        }
      ]
    }
  ]
}
