{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "spilling",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spilling-1.0.0.jar",
          "url": "spilling-1.0.0.jar",
          "size": 60668,
          "sha512": "4e39283e6ff198e442377acbfb5aa597c3add2bd46a33fcc1626f76c672f72d7c7f89d9891432f5047e3171b3f039d09ce1f95d05297faca0c92e047e39ccab3",
          "sha256": "5dff56216d63f569812539362d18e17e59a70d3e8963659fe00892caff75c98b",
          "sha1": "c9fc85d7dd642a119a053f0ba528cba50bbe42fb",
          "md5": "9dbe40dba17ba92bcfee5aead46e76ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spilling-1.0.0.jar",
          "url": "spilling-1.0.0.jar",
          "size": 60668,
          "sha512": "4e39283e6ff198e442377acbfb5aa597c3add2bd46a33fcc1626f76c672f72d7c7f89d9891432f5047e3171b3f039d09ce1f95d05297faca0c92e047e39ccab3",
          "sha256": "5dff56216d63f569812539362d18e17e59a70d3e8963659fe00892caff75c98b",
          "sha1": "c9fc85d7dd642a119a053f0ba528cba50bbe42fb",
          "md5": "9dbe40dba17ba92bcfee5aead46e76ad"
        }
      ]
    }
  ]
}
