{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "spilling",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spilling-1.0.0.jar",
          "url": "spilling-1.0.0.jar",
          "size": 60566,
          "sha512": "bbe3d296449b221b2d0d75167f96035d0ce2afb19e56887608ec44e0f1b4c376d2c2f81ef2ef043e1e2ed5deb2c73da0b85e95e32e4e186d6436ac69d5423dd4",
          "sha256": "b3f247a02ada27e7efa2867734afc1eeb4b42059e2bf3de728d121e078c6c78d",
          "sha1": "2a931f621355091fff138a5f56af2d1043b6059b",
          "md5": "583c2764338a7d24cf46a4f07586ee8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spilling-1.0.0.jar",
          "url": "spilling-1.0.0.jar",
          "size": 60566,
          "sha512": "bbe3d296449b221b2d0d75167f96035d0ce2afb19e56887608ec44e0f1b4c376d2c2f81ef2ef043e1e2ed5deb2c73da0b85e95e32e4e186d6436ac69d5423dd4",
          "sha256": "b3f247a02ada27e7efa2867734afc1eeb4b42059e2bf3de728d121e078c6c78d",
          "sha1": "2a931f621355091fff138a5f56af2d1043b6059b",
          "md5": "583c2764338a7d24cf46a4f07586ee8b"
        }
      ]
    }
  ]
}
