{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "serifier",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "serifier-1.0.0.jar",
          "url": "serifier-1.0.0.jar",
          "size": 108949,
          "sha512": "5502b35d95319c3ad98d67c2c80f17ddd143ce69cb424fe940b4468b895e809997ba8eb558174784ff89d0fd6d16b7e7ddc2a7576c9557c5413776b123051de1",
          "sha256": "b9982cd564a444b1f0a1e579ad7b41474b0b17fc1afc59a8ea55e7437bb4c592",
          "sha1": "1b3a3b2a24985666695b80863befa2920ea68951",
          "md5": "f9836ffe62be775f2bf93acbc1facc34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-vfs2",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-mllib_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-kubernetes_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.simmi.geneset",
          "module": "javafasta",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "serifier-1.0.0.jar",
          "url": "serifier-1.0.0.jar",
          "size": 108949,
          "sha512": "5502b35d95319c3ad98d67c2c80f17ddd143ce69cb424fe940b4468b895e809997ba8eb558174784ff89d0fd6d16b7e7ddc2a7576c9557c5413776b123051de1",
          "sha256": "b9982cd564a444b1f0a1e579ad7b41474b0b17fc1afc59a8ea55e7437bb4c592",
          "sha1": "1b3a3b2a24985666695b80863befa2920ea68951",
          "md5": "f9836ffe62be775f2bf93acbc1facc34"
        }
      ]
    }
  ]
}
