{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "javafasta",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javafasta-1.0.0.jar",
          "url": "javafasta-1.0.0.jar",
          "size": 641751,
          "sha512": "b9e4556a8a45a6a14127f258c05d72d5daa8c7c9172faa544137f2186b45461b1550c3c1557ea4b1945a2abd10357df3b3958a24e03cb86198de799ee291ae6d",
          "sha256": "7026dae6ff1b6f0b07492dea3ef91ed2d69bb6aa2b170cbb3e840038f5aa64cf",
          "sha1": "7b6754871aec84728ce63e50b2e2f0977e6b70e1",
          "md5": "5bca5d669e416b05e49b57e467420630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-all",
          "version": {
            "requires": "0.41"
          }
        },
        {
          "group": "com.github.samtools",
          "module": "htsjdk",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-mllib_2.13",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-kubernetes_2.13",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.0-rc3"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javafasta-1.0.0.jar",
          "url": "javafasta-1.0.0.jar",
          "size": 641751,
          "sha512": "b9e4556a8a45a6a14127f258c05d72d5daa8c7c9172faa544137f2186b45461b1550c3c1557ea4b1945a2abd10357df3b3958a24e03cb86198de799ee291ae6d",
          "sha256": "7026dae6ff1b6f0b07492dea3ef91ed2d69bb6aa2b170cbb3e840038f5aa64cf",
          "sha1": "7b6754871aec84728ce63e50b2e2f0977e6b70e1",
          "md5": "5bca5d669e416b05e49b57e467420630"
        }
      ]
    }
  ]
}
