{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "distann",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "distann-1.0.0.jar",
          "url": "distann-1.0.0.jar",
          "size": 10523509,
          "sha512": "d8e54d61ad3b24f04209dfaaaeab6762f9a5bbe3d31d61bd61b15e15ebab5a103999d180d8cf2bc162065270bf874f7fae33e910ce647db30dbad37f996940cf",
          "sha256": "ff7258ca4dd2625613081b28f8b73b2673de501b44c81fbfc92c3852a23e11d3",
          "sha1": "d186ef24fca35f09b7a0bcf46474a4ffb38fedde",
          "md5": "e0fd937999f33187fe68d58ffaf051ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "javafasta",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "serifier",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "spilling",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.21.9"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.50.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.50.2"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-vfs2",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.0-rc3"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-mllib_2.13",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-kubernetes_2.13",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-graphx_2.13",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.50.2"
          }
        }
      ],
      "files": [
        {
          "name": "distann-1.0.0.jar",
          "url": "distann-1.0.0.jar",
          "size": 10523509,
          "sha512": "d8e54d61ad3b24f04209dfaaaeab6762f9a5bbe3d31d61bd61b15e15ebab5a103999d180d8cf2bc162065270bf874f7fae33e910ce647db30dbad37f996940cf",
          "sha256": "ff7258ca4dd2625613081b28f8b73b2673de501b44c81fbfc92c3852a23e11d3",
          "sha1": "d186ef24fca35f09b7a0bcf46474a4ffb38fedde",
          "md5": "e0fd937999f33187fe68d58ffaf051ba"
        }
      ]
    }
  ]
}
