{
  "formatVersion": "1.1",
  "component": {
    "group": "org.simmi.geneset",
    "module": "distann",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "distann-1.0.0.jar",
          "url": "distann-1.0.0.jar",
          "size": 10538457,
          "sha512": "c1bf9e43c1de128dd9d8cba2eabab21880299dcc35aff43543cd56721d33d31fa9c1b92762fe1b92802b654d357cfd25b4da9953416ab20f642d513ce1a057f5",
          "sha256": "5499835ae20a42da3ebb7008a340cee3787ab65b7b80d8e38fe29fb4c4c6731e",
          "sha1": "683edf21a34bc5332c5c1f45840a5d09cdcd4e35",
          "md5": "35c48f9e52e867543369bf5c86eb87f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "20.0.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac-aarch64"
            }
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "javafasta",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "serifier",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "spilling",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.simmi.geneset",
          "module": "Treedraw",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.21.9"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.50.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.50.2"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-vfs2",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.0-rc3"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-mllib_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-kubernetes_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-graphx_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hive-thriftserver_2.13",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson",
              "module": "*"
            },
            {
              "group": "avro-mapred",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.50.2"
          }
        }
      ],
      "files": [
        {
          "name": "distann-1.0.0.jar",
          "url": "distann-1.0.0.jar",
          "size": 10538457,
          "sha512": "c1bf9e43c1de128dd9d8cba2eabab21880299dcc35aff43543cd56721d33d31fa9c1b92762fe1b92802b654d357cfd25b4da9953416ab20f642d513ce1a057f5",
          "sha256": "5499835ae20a42da3ebb7008a340cee3787ab65b7b80d8e38fe29fb4c4c6731e",
          "sha1": "683edf21a34bc5332c5c1f45840a5d09cdcd4e35",
          "md5": "35c48f9e52e867543369bf5c86eb87f2"
        }
      ]
    }
  ]
}
